language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

  before_script:
  - npm install -g @angular/cli --yes

script:
  - npm run lint
  - xvfb-run npm run test
  - npm run build
  - xvfb-run npm run e2e
